services:
  - type: web
    name: moodify
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SPOTIPY_CLIENT_ID
        value: 9001e8d19905435598ed117cbb46fd8e
      - key: SPOTIPY_CLIENT_SECRET
        value: ef0ab8129cba4852948fb4c16ea2b47d
      - key: SPOTIPY_REDIRECT_URI
        value: https://moodify-0w8i.onrender.com/callback


